### PR TITLE
Lyrics app #108

### LINKED ISSUE #108: song-lyrics-app
# Song-Lyrics-Search-App

A browser based application using JavaScript to search songs, artists and lyrics by typing out the singer's name using the [lyrics.ovh](https://lyrics.ovh) API .

<hr>

## Technologies Used

``` JavaScript, Html, CSS ```

<hr>

## API

``` lyrics.ovh ```

<hr>

## Project Specifications

- Displayed UI with song/artist input
- Fetch songs/artists and put in DOM using ``` lyrics.ovh ``` API.
- Added pagination .
- Added get lyrics functionality and display functions in DOM

Screenshot (738)
Screenshot (739)

<hr>

## Alternatives considered
- react app but will be wat to heavy and lots of dependencies

### PR DESCRIPTION
**Pull request by chinmayaAgrawal**
# Lyrics-App

A browser based application using JavaScript to search songs, artists and lyrics by typing out the singer's name using the [lyrics.ovh](https://lyrics.ovh) API .

<hr>

Screenshot (738)
Screenshot (739)

<hr>

## Technologies Used

``` JavaScript, Html, CSS ```

<hr>

## Project Specifications

- Displayed UI with song/artist input
- Fetch songs/artists and put in DOM using ``` lyrics.ovh ``` API.
- Added pagination .
- Added get lyrics functionality and display functions in DOM

<hr>

## Issue 

Fixes #108 

<hr>

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

<hr>

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by anjali1102** [comment]
Hey @chinmayaAgrawal  There are some conflicting merge issues in expense-tracker/readme.md

**Comment by chinmayaAgrawal** [comment]
@anjali1102 I just deleted the folder as it was in other branch but why is it showing conflicting files as this file does not even exists in this branch. How to resolve this?

**Comment by anjali1102** [comment]
Ok i will review

**Comment by chinmayaAgrawal** [comment]
yes please

**Comment by anjali1102** [comment]
unable to merge in any way.

**Comment by anjali1102** [comment]
Try to give clean PR again 
Me closing this @chinmayaAgrawal

**Pull request closed without merging**
