### PR TITLE
Added Simon Game

### PR DESCRIPTION
**Pull request by Gaurangseven**
Simon is an electronic game of memory skill invented by Ralph H. Baer and Howard J. Morrison, working for toy design firm Marvin Glass and Associates,[1] with software programming by Lenny Cope. The device creates a series of tones and lights and requires a user to repeat the sequence. If the user succeeds, the series becomes progressively longer and more complex. Once the user fails or the time limit runs out, the game is over.

This is a project a did while learning Web Development.

### CODE REVIEW

**Comment by anjali1102** [comment]
> # Description      
> Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.
> 
> Fixes #(issue_no)   **Add issue no here/if  not then raise**
> 
> Replace `issue_no` with the issue number which is fixed in this PR
> 
> ## Type of change
> _Please delete options that are not relevant._
> 
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [ ]  New feature (non-breaking change which adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [ ]  This change requires a documentation update
> * [ ]  Documentation Update
> 
> # Checklist:
> * [ ]  My code follows the style guidelines(Clean Code) of this project
> * [ ]  I have performed a self-review of my own code
> * [ ]  I have commented my code, particularly in hard-to-understand areas
> * [ ]  I have created a helpful and easy to understand `README.md`
> * [ ]  I have made corresponding changes to the documentation
> * [ ]  My changes generate no new warnings
> * [ ]  I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

**Comment by anjali1102** [comment]
@Gaurangseven

**Comment by Gaurangseven** [comment]
@anjali1102 hey I have made changes to it please approve and accept.

**Comment by anjali1102** [comment]
@Gaurangseven 
Raise New issue  [HERE](https://github.com/anjali1102/Hacktober2021/issues)
with project name.

And then Add that issue number above in description (like Fixes #your_issue_number)

**Comment by anjali1102** [comment]
Don't worry I will accept, just saying so it can't be rejected in review time

**Comment by Gaurangseven** [comment]
> @Gaurangseven Raise New issue [HERE](https://github.com/anjali1102/Hacktober2021/issues) with project name, a bit about
> 
> And then Add that issue number above in description (like Fixes #your_issue_number)

Okay Sure

**Comment by Gaurangseven** [comment]
@anjali1102 thanks for helping out and accepting it,It was my first hacktoberfest i was bit confused ,Thanks again alot

**Pull request merged**
